#!/usr/bin/env python3
"""
Demo script to show the blog writing agent execution flow.
This demonstrates the structure without requiring API keys.
"""

import os
from dotenv import load_dotenv

load_dotenv()

print("=" * 100)
print("BLOG WRITING AGENT - EXECUTION DEMONSTRATION")
print("=" * 100)
print()

print("Step 1: Checking environment setup...")
print("-" * 100)

openai_key = os.getenv("OPENAI_API_KEY")
tavily_key = os.getenv("TAVILY_API_KEY")
google_key = os.getenv("GOOGLE_API_KEY")

print(f"✓ OPENAI_API_KEY: {'SET (required for LLM calls)' if openai_key else 'NOT SET (required)'}")
print(f"✓ TAVILY_API_KEY: {'SET (optional, for web research)' if tavily_key else 'NOT SET (optional)'}")
print(f"✓ GOOGLE_API_KEY: {'SET (optional, for image generation)' if google_key else 'NOT SET (optional)'}")
print()

if not openai_key:
    print("⚠️  WARNING: OPENAI_API_KEY is required to run the agent.")
    print("   Please set it in a .env file or export it as an environment variable.")
    print("   Example: export OPENAI_API_KEY='your-key-here'")
    print()
    print("=" * 100)
    print("EXECUTION FLOW (what would happen with API keys):")
    print("=" * 100)
    print()
    print("1. Router Node:")
    print("   - Analyzes topic: 'Write a blog on Self Attention'")
    print("   - Decides: closed_book mode (evergreen topic, no research needed)")
    print("   - Output: needs_research=False, mode='closed_book'")
    print()
    print("2. Research Node:")
    print("   - SKIPPED (needs_research=False)")
    print()
    print("3. Orchestrator Node:")
    print("   - Creates blog plan with 5-9 sections")
    print("   - Each section has:")
    print("     * Goal (what reader should understand)")
    print("     * 3-6 concrete bullets to cover")
    print("     * Target word count (120-550 words)")
    print("     * Flags for research/citations/code needs")
    print()
    print("4. Fanout:")
    print("   - Distributes tasks to worker nodes in parallel")
    print("   - Each worker gets one section to write")
    print()
    print("5. Worker Nodes (parallel execution):")
    print("   - Each worker writes one section following the plan")
    print("   - Sections are written in Markdown format")
    print("   - Word count targets are respected")
    print()
    print("6. Reducer Subgraph:")
    print("   a. Merge Content: Combines all sections into one document")
    print("   b. Decide Images: Determines if diagrams/images are needed")
    print("   c. Generate & Place Images: Creates images and inserts them")
    print()
    print("7. Output:")
    print("   - Saves blog as: {blog_title}.md")
    print("   - Creates images/ directory if images were generated")
    print("   - Returns state object with full execution details")
    print()
    print("=" * 100)
    print("TO RUN THE ACTUAL AGENT:")
    print("=" * 100)
    print("1. Set OPENAI_API_KEY in .env file or environment")
    print("2. (Optional) Set TAVILY_API_KEY for web research")
    print("3. (Optional) Set GOOGLE_API_KEY for image generation")
    print("4. Run: python3 run_blog_agent.py")
    print()
    print("Example .env file:")
    print("  OPENAI_API_KEY=sk-...")
    print("  TAVILY_API_KEY=tvly-...")
    print("  GOOGLE_API_KEY=...")
    print()
else:
    print("✓ All required API keys are set!")
    print()
    print("=" * 100)
    print("READY TO RUN")
    print("=" * 100)
    print()
    print("To execute the agent, run:")
    print("  python3 run_blog_agent.py")
    print()
    print("Or use the notebook:")
    print("  jupyter notebook blog_writing_agent_complete.ipynb")
    print()
